version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: shopping_cart_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ekart-mysql

  app:
    image: vijayabharathi28/ekart:latest
    container_name: ekart
    ports:
      - "8070:8070"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopping_cart_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - ekart-mysql

volumes:
  mysql-data:

networks:
  ekart-mysql:
    driver: bridge
