services:
  shop:
    image: vijayabharathi28/ekart:latest
    ports:
      - "8070:8070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://my-mysql-container:3306/shopping_cart_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - mynetwork
    entrypoint: ["sh", "-c", "until mysqladmin ping -h my-mysql-container --silent; do echo waiting for mysql; sleep 2; done; java -jar /app.jar"]

networks:
  mynetwork:
    external: true  # Use the previously created external network
