version: '3'
services:
  shop:
    image: vijayabharathi28/ekart:latest
    ports:
      - "8070:8070"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shopping_cart_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - mynetwork
    entrypoint: ["sh", "-c", "until mysqladmin ping -h mysql --silent; do echo waiting for mysql; sleep 2; done; java -jar /app.jar"]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_cart_db
    ports:
      - "3308:3306"
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s

networks:
  mynetwork:
    external: true  # Use the previously created external network
