version: '3'
services:
  shop:
    image: vijayabharathi28/ekart:latest
    ports:
      - "8070:8070"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shopping_cart_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_cart_db
    ports:
      - "3308:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
